server:
  servlet:
    context-path: /starwars-api

  port: ${PORT:8080}

swapi:
  url: https://swapi.dev/api
  # url: https://swapi-deno.azurewebsites.net/api

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:starwarsapidb
  output:
  ansi:
    enabled: DETECT

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
        cache : TRACE
        security: DEBUG
      hibernate: WARN
    br:
      com:
        massao: DEBUG


# jwt
jwt:
  secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
  expiration: 86400000